initial commit action

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,44 +1,42 @@
-name: Portfolio CICD pipeline
+name: My Portfolio
 
 on: push
+  
+       
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v4  
 
-      - name: build docker image
+      - name: Build image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:${{ github.run_number }} .
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest .
-
-      - name: login to docker hub
+         docker build -t ${{secrets.DOCKER_USERNAME}}/my-portfolio-app:${{github.run_number}} .
+         docker build -t ${{secrets.DOCKER_USERNAME}}/my-portfolio-app .
+      - name: Docker login
         uses: docker/login-action@v4
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: list docker images
-        run: docker images
-
-      - name: push docker image to registry
+      - name: Push image to registry
         run: |
-          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:${{ github.run_number }}
-          docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest
-
+         docker push ${{secrets.DOCKER_USERNAME}}/my-portfolio-app:${{github.run_number}}
+         docker push ${{secrets.DOCKER_USERNAME}}/my-portfolio-app
+      
   deploy:
-    runs-on: ubuntu-latest
     needs: build
+    runs-on: ubuntu-latest
     steps:
-      - name: SSH to Linux and RUN container
+      - name: SSh to Linux and run container
         uses: appleboy/ssh-action@v1
         with:
-          host: "${{secrets.HOST}}"
-          username: "${{secrets.SSH_USERNAME}}"
-          key: "${{ secrets.SSH_PRIVATE_KEY}}"
-          port: 22
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.PRIVATE_KEY }}
           script: |
-            docker rm -f my-portfolio-app || echo "Container not found, skipping removal"
-            docker run -d --name my-portfolio-app -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app
+              docker rm -f portfolio || echo "Container not found, skipping removal."
+              docker rmi -f ${{secrets.DOCKER_USERNAME}}/my-portfolio-app || echo "image do not exist"
+              docker run -d --name portfolio -p 8080:80 ${{secrets.DOCKER_USERNAME}}/my-portfolio-app
