initial commit action

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,58 +1,44 @@
-name: Portfolio CICD Pipeline
+name: Portfolio CICD pipeline
 
-on:
-  push:
-    branches:
-      - main
+on: push
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
+      - name: checkout code
         uses: actions/checkout@v4
 
-      - name: Build Docker image
+      - name: build docker image
         run: |
           docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:${{ github.run_number }} .
-          docker tag ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:${{ github.run_number }} \
-            ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest .
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
+      - name: login to docker hub
+        uses: docker/login-action@v4
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: List Docker images
+      - name: list docker images
         run: docker images
 
-      - name: Push Docker image
+      - name: push docker image to registry
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:${{ github.run_number }}
           docker push ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest
 
-
   deploy:
     runs-on: ubuntu-latest
     needs: build
-
     steps:
-      - name: SSH to Linux server and run container
+      - name: SSH to Linux and RUN container
         uses: appleboy/ssh-action@v1
         with:
-          host: ${{ secrets.HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          host: "${{secrets.HOST}}"
+          username: "${{secrets.SSH_USERNAME}}"
+          key: "${{ secrets.SSH_PRIVATE_KEY}}"
           port: 22
           script: |
-            docker pull ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest
-
-            docker rm -f my-portfolio-app || true
-
-            docker run -d \
-              --name my-portfolio-app \
-              -p 8080:80 \
-              ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app:latest
+            docker rm -f my-portfolio-app || echo "Container not found, skipping removal"
+            docker run -d --name my-portfolio-app -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/my-portfolio-app
